# Generated by Django 3.1.2 on 2020-10-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='station_id',
            field=models.CharField(max_length=16),
        ),
    ]
